#pragma once

#define ERROR_WSAFAILED 2
#define ERROR_SOCKETFAILED 3
#define ERROR_BIND_FAILED 4
#define ERROR_LISTEN_FAILED 5
#define ERROR_ACCEPT_FAILED 6
#define ERROR_SEND_FAILED 7

#define DISCONNECTED 250
